### ISSUE TITLE
Some styling suggestions

### ISSUE THREAD

**Issue by r-jo** [dev-bhatia/dev-bhatia.github.io#2]
**Suggestions**
- Move linkedin to footer
- Have current page link underlined to notify user what page they are on
- Increase or change colorscheme for better contrast. The light green and gray for the links do not show up well on bright screens. I suggest either sienna red or navy blue or the blue that Apple uses.

**Comment by dev-bhatia** [comment]
Regarding styling, what are your thought on an automatic dark mode based on time of day for the user. I've tried something like that in another repo (dev-bhatia/public_html).

**Comment by r-jo** [comment]
That would be really neat. Some other ways you can try implementing a dark mode is using `@media (prefers-color-scheme: dark)` which will match the user's OS theme or putting a button to allow them to change at will but that one is a bit more complex.
