### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by r-jo** [dev-bhatia/dev-bhatia.github.io#3]
It isn't advisable to have your email displayed as plain text because web crawlers and bots like to copy it and send you spam. I suggest adding a click to copy function or click to open mailbox attribute to your link.

**Comment by dev-bhatia** [comment]
I can remover the email from the footer. On index.html I have a href to open mailbox when clicking on my email. Would this also not be advised?

**Comment by r-jo** [comment]
Href works fine as long as no one can read it in plain text. Personally, I use clipboard.js and some javascript because I've received complaints about how users hate it opening up the default mail app such as on macOS or iOS or windows machines.
